# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Startup Task
    init: yarn install
    command: bin/setup && bin/dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
  - name: PostgreSQL server
    port: 5432
    onOpen: ignore

vscode:
  extensions:
    - aki77.rails-db-schema
    - aliariff.vscode-erb-beautify
    - castwide.solargraph
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - rebornix.ruby
    - wingrunr21.vscode-ruby
